# -*- coding: utf-8 -*-
"""Spam_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEiw1O_EnhONF7ts9oowtd8UursekF7m
"""

import pandas as pd
import numpy as np

import pandas as pd

# Raw file URL
url = "https://raw.githubusercontent.com/AkilaMohan/Implementation-of-SVM-For-Spam-Mail-Detection/main/spam%20(1).csv"

# Load the CSV into a DataFrame
df = pd.read_csv(url, encoding='ISO-8859-1')
df=pd.DataFrame(df)
# Display the first few rows
df

df=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

df=df.reset_index(drop=True)
df.describe()

df.columns=['labels','msg']
#there is a duplicates in v2 lets remove it
df=df.drop_duplicates(subset='msg',keep='first')
df.describe()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#split feature and target
x=df['msg']
y=df['labels']

#convert text intonumerical
vectorizer=CountVectorizer()
x_features = vectorizer.fit_transform(x)

#split it
x_train,x_test,y_train,y_test=train_test_split(x_features,y,test_size=0.20,random_state=42)

#train moedl
model=LogisticRegression()
model.fit(x_train,y_train)

y_pred= model.predict(x_test)

print("Accuracy: \n",accuracy_score(y_test,y_pred))
print("confusion Matrix: \n",confusion_matrix(y_test,y_pred))
print("Classification report: \n", classification_report(y_test,y_pred))

df_pred=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
df_pred

df_pred["conclusion"]=(df_pred["Actual"]==df_pred["Predicted"] ).astype(int)
df_pred